### ISSUE TITLE
How to stop script running ?

### ISSUE THREAD

**Issue by Denis-Evseev** [cppmyk/stargate-bridger#10]
Hi, thank you amazing work on the repository.

Do you know how to stop the script running in the VS Terminal?
The usual Ctrl + C is not working.

**Comment by cppmyk** [comment]
You should probably press Ctrl + C one more time to kill all the running threads.

**Comment by Denis-Evseev** [comment]
Unfortunately, it does not work for me, have to kill via Task Manager, which is fine for now.

**Comment by Denis-Evseev** [comment]
@cppmyk is there anything I can do for you to improve the project?
Do you have a similar project for zkSync or Straknet?

**Comment by cppmyk** [comment]
> Unfortunately, it does not work for me, have to kill via Task Manager, which is fine for now.

🤔 It's strange because pressing Ctrl + C one more time always worked for me. Maybe you have an interesting terminal Xd

> @cppmyk is there anything I can do for you to improve the project? Do you have a similar project for zkSync or Straknet?

Thanks for the proposition, but I don't see the point in continuing to work on this project.
Speaking about other projects - I don't have anything publicly available for now. If I publish smth - you will see it in my telegram channel and in this GitHub account :)
